//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootry.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Tag = new HashSet<Tag>();
            this.Comment = new HashSet<Comment>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        [AllowHtml]
        public string PostContent { get; set; }
        public string Image { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int ViewCount { get; set; }
        public int CategoryID { get; set; }
        public int WriterID { get; set; }
        public string SeoTitle { get; set; }
        public string Summary { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Writer Writer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
